language: php
php:
- 5.4
- 5.5
- 5.6
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
- WP_VERSION=4.0 WP_MULTISITE=0
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
notifications:
  slack:
    secure: IJnwZK7KEmW573UDtfZ2l/DHAz5JmGMYTvWa5H0pYaGzKWrayYrsfdTSFUMxud13tcyo+iSB07MxlQPywu5QarnbNt7Ptqw75qcn/LYCfiHRN3/nhtnh6nZ7equPNXTZsEyUorPuts3t/XKc30k3nvt3KAHGYqVDiY2q7C4je9M=
